// GENERATED by `node scripts/generate-collection-schema.mjs articles` from
// public/admin/schema.js's "_articles" entry + content/articles.json. Re-run after
// changing the admin's field layout for this collection rather than hand-editing the field
// map below — the generator fails loudly if the two sources disagree, hand edits here can't.
import type { ItemFieldMap } from './codec';

export const ARTICLES_FIELDS = {
  "kind": { kind: "text", type: "text", label: "النوع" },
  "date": { kind: "text", type: "text", label: "التاريخ" },
  "read": { kind: "text", type: "text", label: "مدة القراءة" },
  "ph": { kind: "boolean", type: "boolean", label: "بيانات تجريبية (مؤقتة)" },
  "img": { kind: "image", type: "image", label: "الصورة" },
  "title": { kind: "text", type: "text", label: "العنوان" },
  "lede": { kind: "text", type: "long", label: "المقدمة" },
  "body": { kind: "list", type: "list", label: "عنوان الفقرة", itemFields: {
    "h": { kind: "text", type: "text", label: "عنوان الفقرة" },
    "p": { kind: "text", type: "text", label: "نص الفقرة" },
  } },
  "quote": { kind: "text", type: "text", label: "الاقتباس" },
  "quoteBy": { kind: "text", type: "text", label: "قائل الاقتباس" },
  "tags": { kind: "list", type: "text", label: "الوسوم", itemKind: "text" },
} as const satisfies ItemFieldMap;

const ARTICLES_COLLECTION = {
  label: "الأخبار والمقالات",
  file: "assets/js/article-data.js",
  store: "articles",
  addable: false,
  fields: ARTICLES_FIELDS,
  newItem: {"kind":{"en":"","ar":""},"date":{"en":"","ar":""},"read":{"en":"","ar":""},"ph":false,"img":{"src":""},"title":{"en":"","ar":""},"lede":{"en":"","ar":""},"body":[],"quote":{"en":"","ar":""},"quoteBy":{"en":"","ar":""},"tags":[]},
};

export default ARTICLES_COLLECTION;
