// GENERATED by `node scripts/generate-collection-schema.mjs challenges` from
// public/admin/schema.js's "_challenges" entry + content/challenges.json. Re-run after
// changing the admin's field layout for this collection rather than hand-editing the field
// map below — the generator fails loudly if the two sources disagree, hand edits here can't.
import type { ItemFieldMap } from './codec';

export const CHALLENGES_FIELDS = {
  "title": { kind: "text", type: "text", label: "العنوان" },
  "description": { kind: "text", type: "long", label: "الوصف" },
  "image": { kind: "image", type: "image", label: "الصورة" },
} as const satisfies ItemFieldMap;

const CHALLENGES_COLLECTION = {
  label: "التحديات الوطنية",
  file: "assets/js/challenges-data.js",
  store: "challenges",
  addable: true,
  deletable: true,
  fields: CHALLENGES_FIELDS,
  newItem: {"title":{"en":"New challenge","ar":"تحدٍّ جديد"},"description":{"en":"","ar":""},"image":{"src":""}},
};

export default CHALLENGES_COLLECTION;
