// GENERATED by `node scripts/generate-collection-schema.mjs events` from
// public/admin/schema.js's "_events" entry + content/events.json. Re-run after
// changing the admin's field layout for this collection rather than hand-editing the field
// map below — the generator fails loudly if the two sources disagree, hand edits here can't.
import type { ItemFieldMap } from './codec';

export const EVENTS_FIELDS = {
  "day": { kind: "value", type: "text", label: "اليوم (رقم)" },
  "month": { kind: "text", type: "text", label: "الشهر والسنة" },
  "title": { kind: "text", type: "text", label: "عنوان الفعالية" },
  "desc": { kind: "text", type: "long", label: "وصف مختصر" },
  "link": { kind: "value", type: "url", label: "رابط زر «التفاصيل»" },
} as const satisfies ItemFieldMap;

const EVENTS_COLLECTION = {
  label: "الفعاليات والمعارض",
  file: "assets/js/events-data.js",
  store: "events",
  addable: true,
  fields: EVENTS_FIELDS,
  newItem: {"day":"01","month":{"en":"JAN 2027","ar":"يناير 2027"},"title":{"en":"New event","ar":"فعالية جديدة"},"desc":{"en":"Short description of the event.","ar":"وصف مختصر للفعالية."},"link":"register-interest.html"},
};

export default EVENTS_COLLECTION;
