// GENERATED by `node scripts/generate-collection-schema.mjs groups` from
// public/admin/schema.js's "_groups" entry + content/groups.json. Re-run after
// changing the admin's field layout for this collection rather than hand-editing the field
// map below — the generator fails loudly if the two sources disagree, hand edits here can't.
import type { ItemFieldMap } from './codec';

export const GROUPS_FIELDS = {
  "name": { kind: "text", type: "text", label: "اسم المجموعة" },
  "scope": { kind: "text", type: "long", label: "نطاق العمل" },
  "img": { kind: "image", type: "image", label: "img" },
  "no": { kind: "value", type: "text", label: "الرقم التسلسلي" },
  "ch": { kind: "value", type: "text", label: "فئة التحدي" },
} as const satisfies ItemFieldMap;

const GROUPS_COLLECTION = {
  label: "بيانات مجموعات العمل التسع",
  file: "assets/js/wg-data.js",
  store: "groups",
  addable: true,
  deletable: true,
  fields: GROUPS_FIELDS,
  newItem: {"name":{"en":"New working group","ar":"مجموعة عمل جديدة"},"scope":{"en":"Short description of the working group.","ar":"نبذة مختصرة عن مجموعة العمل."},"img":{"src":""},"no":"","ch":""},
};

export default GROUPS_COLLECTION;
