// GENERATED by `node scripts/generate-collection-schema.mjs members` from
// public/admin/schema.js's "_members" entry + content/members.json. Re-run after
// changing the admin's field layout for this collection rather than hand-editing the field
// map below — the generator fails loudly if the two sources disagree, hand edits here can't.
import type { ItemFieldMap } from './codec';

export const MEMBERS_FIELDS = {
  "name": { kind: "text", type: "text", label: "اسم الجهة" },
  "logo": { kind: "image", type: "image", label: "الشعار" },
  "ini": { kind: "value", type: "text", label: "الأحرف الأولى (لعرض بديل عن الشعار)" },
  "cat": { kind: "text", type: "text", label: "التصنيف" },
  "role": { kind: "text", type: "text", label: "الدور في التحالف" },
  "sector": { kind: "text", type: "text", label: "مجال التركيز" },
  "since": { kind: "value", type: "text", label: "عضو منذ" },
  "short": { kind: "value", type: "text", label: "نبذة مختصرة" },
  "bio": { kind: "text", type: "long", label: "نبذة تعريفية" },
} as const satisfies ItemFieldMap;

const MEMBERS_COLLECTION = {
  label: "بيانات المتحالفين",
  file: "assets/js/members-data.js",
  store: "members",
  addable: true,
  fields: MEMBERS_FIELDS,
  newItem: {"name":{"en":"New member","ar":"عضو جديد"},"logo":{"src":""},"ini":"","cat":{"en":"","ar":""},"role":{"en":"","ar":""},"sector":{"en":"","ar":""},"since":"","short":"","bio":{"en":"","ar":""}},
};

export default MEMBERS_COLLECTION;
