// GENERATED by `node scripts/generate-collection-schema.mjs partners` from
// public/admin/schema.js's "_partners" entry + content/partners.json. Re-run after
// changing the admin's field layout for this collection rather than hand-editing the field
// map below — the generator fails loudly if the two sources disagree, hand edits here can't.
import type { ItemFieldMap } from './codec';

export const PARTNERS_FIELDS = {
  "name": { kind: "text", type: "text", label: "اسم الشريك" },
  "logo": { kind: "image", type: "image", label: "الشعار" },
  "url": { kind: "value", type: "text", label: "رابط الشريك (اختياري)" },
} as const satisfies ItemFieldMap;

const PARTNERS_COLLECTION = {
  label: "الشراكات الاستراتيجية",
  file: "assets/js/partners-data.js",
  store: "partners",
  addable: true,
  deletable: true,
  fields: PARTNERS_FIELDS,
  newItem: {"name":{"en":"New partner","ar":"شريك جديد"},"logo":{"src":""},"url":""},
};

export default PARTNERS_COLLECTION;
