// GENERATED by `node scripts/generate-collection-schema.mjs roles` from
// public/admin/schema.js's "_roles" entry + content/roles.json. Re-run after
// changing the admin's field layout for this collection rather than hand-editing the field
// map below — the generator fails loudly if the two sources disagree, hand edits here can't.
import type { ItemFieldMap } from './codec';

export const ROLES_FIELDS = {
  "title": { kind: "text", type: "text", label: "العنوان" },
  "description": { kind: "text", type: "long", label: "الوصف" },
} as const satisfies ItemFieldMap;

const ROLES_COLLECTION = {
  label: "الأدوار المؤسسية للتحالف",
  file: "assets/js/roles-data.js",
  store: "roles",
  addable: true,
  deletable: true,
  fields: ROLES_FIELDS,
  newItem: {"title":{"en":"New role","ar":"دور جديد"},"description":{"en":"","ar":""}},
};

export default ROLES_COLLECTION;
