// GENERATED by `node scripts/generate-page-schema.mjs about` from public/admin/schema.js
// + content/about.json. Re-run after changing the admin's field/section layout for this
// page rather than hand-editing the field list below — the generator fails loudly if the
// two sources disagree, hand edits here can't.
import type { FieldMap } from './codec';

export const ABOUT_FIELDS = {
  "t001-الرئيسية": { kind: "text", tag: "a", type: "text", label: "الرئيسية" },
  "t002-عن-التحالف": { kind: "text", tag: "h1", type: "text", label: "عن التحالف" },
  "t003-منصة-وطنية-للتعاون-والتنسي": { kind: "text", tag: "p", type: "long", label: "منصة وطنية للتعاون والتنسيق وتبادل المعرفة في ابتكار تقنيات الزراعة وا" },
  "t004-الرسالة-والرؤية": { kind: "text", tag: "p", type: "text", label: "الرسالة والرؤية" },
  "t005-منصة-وطنية-لتسريع-تبنّي-تق": { kind: "text", tag: "h2", type: "text", label: "منصة وطنية لتسريع تبنّي تقنيات الزراعة والغذاء" },
  "t006-تأسّس-التحالف-السعودي-لتقن": { kind: "text", tag: "p", type: "long", label: "تأسّس التحالف السعودي لتقنيات الزراعة والغذاء كمنصّة وطنية للتعاون وال" },
  "t007-يُعدّ-التحالف-أحد-أبرز-مخر": { kind: "text", tag: "p", type: "long", label: "يُعدّ التحالف أحد أبرز مخرجات الخطة التنفيذية للبحث والابتكار في وزارة" },
  "i008-reelposter": { kind: "image", tag: "img", type: "image", label: "reel-poster.jpg" },
  "t009-شغّل-الفيديو": { kind: "text", tag: "span", type: "text", label: "شغّل الفيديو" },
  "t010-٢٠-ثانية-بلا-صوت": { kind: "text", tag: "span", type: "text", label: "٢٠ ثانية · بلا صوت" },
  "t011-قريبًا": { kind: "text", tag: "b", type: "text", label: "قريبًا" },
  "t012-Soon": { kind: "text", tag: "b", type: "text", label: "Soon" },
  "t013-قريبًا": { kind: "text", tag: "b", type: "text", label: "قريبًا" },
  "t014-Soon": { kind: "text", tag: "b", type: "text", label: "Soon" },
  "t015-نظرة-عامة": { kind: "text", tag: "h2", type: "text", label: "نظرة عامة" },
  "t016-مجموعة-عمل-مستهدفة": { kind: "text", tag: "p", type: "text", label: "مجموعة عمل مستهدفة" },
  "t017-أدوار-مؤسسية-أساسية": { kind: "text", tag: "p", type: "text", label: "أدوار مؤسسية أساسية" },
  "t018-قطاعات-ممثَّلة": { kind: "text", tag: "p", type: "text", label: "قطاعات ممثَّلة" },
  "t019-استراتيجيات-وطنية-متوائمة": { kind: "text", tag: "p", type: "text", label: "استراتيجيات وطنية متوائمة" },
  "t020-السياق-الوطني": { kind: "text", tag: "p", type: "text", label: "السياق الوطني" },
  "t021-تحديات-تجعل-الابتكار-ضرورة": { kind: "text", tag: "h2", type: "text", label: "تحديات تجعل الابتكار ضرورة" },
  "t022-تواجه-أنظمة-الزراعة-والغذا": { kind: "text", tag: "p", type: "long", label: "تواجه أنظمة الزراعة والغذاء في المملكة تحديات كبيرة، تخلق مجتمعةً دافع" },
  "t023-استعرض-مجموعات-العمل": { kind: "text", tag: "span", type: "text", label: "استعرض مجموعات العمل" },
  "t039-الأدوار-المؤسسية": { kind: "text", tag: "p", type: "text", label: "الأدوار المؤسسية" },
  "t040-أربعة-أدوار-توجّه-عمل-التح": { kind: "text", tag: "h2", type: "text", label: "أربعة أدوار توجّه عمل التحالف" },
  "t041-انبثق-التحالف-عن-الخطة-الت": { kind: "text", tag: "p", type: "long", label: "انبثق التحالف عن الخطة التنفيذية للبحث والابتكار بوزارة البيئة والمياه" },
  "i050-phmembership": { kind: "image", tag: "img", type: "image", label: "ph-membership.svg" },
  "t051-البيان-التأسيسي": { kind: "text", tag: "p", type: "text", label: "البيان التأسيسي" },
  "t052-يمثّل-تأسيسه-فرصة-تاريخية-": { kind: "text", tag: "h3", type: "long", label: "«يمثّل تأسيسه فرصة تاريخية لتسخير الذكاء الجماعي والقدرات المتنوعة وال" },
  "t053-تعرّف-على-المتحالفين": { kind: "text", tag: "span", type: "text", label: "تعرّف على الأعضاء" },
} as const satisfies FieldMap;

export const ABOUT_SECTIONS = [
  {
    key: "section-1",
    label: "ترويسة الصفحة",
    fields: ["t001-الرئيسية","t002-عن-التحالف","t003-منصة-وطنية-للتعاون-والتنسي"],
    cards: [

    ],
  },
  {
    key: "section-2",
    label: "من نحن",
    fields: ["t004-الرسالة-والرؤية","t005-منصة-وطنية-لتسريع-تبنّي-تق","t006-تأسّس-التحالف-السعودي-لتقن","t007-يُعدّ-التحالف-أحد-أبرز-مخر","i008-reelposter","t009-شغّل-الفيديو","t010-٢٠-ثانية-بلا-صوت"],
    cards: [

    ],
  },
  {
    key: "section-3",
    label: "رسالتنا ورؤيتنا",
    fields: ["t011-قريبًا","t012-Soon","t013-قريبًا","t014-Soon","t015-نظرة-عامة"],
    cards: [
      { key: "section-3::85", label: "مجموعة عمل مستهدفة", fields: ["t016-مجموعة-عمل-مستهدفة"] },
      { key: "section-3::88", label: "أدوار مؤسسية أساسية", fields: ["t017-أدوار-مؤسسية-أساسية"] },
      { key: "section-3::91", label: "قطاعات ممثَّلة", fields: ["t018-قطاعات-ممثَّلة"] },
      { key: "section-3::94", label: "استراتيجيات وطنية متوائمة", fields: ["t019-استراتيجيات-وطنية-متوائمة"] },
    ],
  },
  {
    key: "section-4",
    label: "ما نؤمن به",
    fields: ["t020-السياق-الوطني","t021-تحديات-تجعل-الابتكار-ضرورة","t022-تواجه-أنظمة-الزراعة-والغذا","t023-استعرض-مجموعات-العمل"],
    cards: [

    ],
  },
  {
    key: "section-5",
    label: "مسيرتنا",
    fields: ["t039-الأدوار-المؤسسية","t040-أربعة-أدوار-توجّه-عمل-التح","t041-انبثق-التحالف-عن-الخطة-الت"],
    cards: [

    ],
  },
  {
    key: "section-6",
    label: "لافتة الانضمام",
    fields: ["i050-phmembership","t051-البيان-التأسيسي","t052-يمثّل-تأسيسه-فرصة-تاريخية-","t053-تعرّف-على-المتحالفين"],
    cards: [

    ],
  },
] as const;

const ABOUT_PAGE = {
  label: "عن التحالف",
  file: "about.html",
  apiBacked: true as const,
  fields: ABOUT_FIELDS,
  sections: ABOUT_SECTIONS,
};

export default ABOUT_PAGE;
