// GENERATED by `node scripts/generate-page-schema.mjs about` from public/admin/schema.js
// + content/about.json. Re-run after changing the admin's field/section layout for this
// page rather than hand-editing the field list below — the generator fails loudly if the
// two sources disagree, hand edits here can't.
import type { FieldMap } from './codec';

export const ABOUT_FIELDS = {
  "t001-الرئيسية": { kind: "text", tag: "a", type: "text", label: "الرئيسية" },
  "t002-عن-التحالف": { kind: "text", tag: "h1", type: "text", label: "عن التحالف" },
  "t003-منصة-وطنية-للتعاون-والتنسي": { kind: "text", tag: "p", type: "long", label: "منصة وطنية للتعاون والتنسيق وتبادل المعرفة في ابتكار تقنيات الزراعة وا" },
  "t004-الرسالة-والرؤية": { kind: "text", tag: "p", type: "text", label: "الرسالة والرؤية" },
  "t005-منصة-وطنية-لتسريع-تبنّي-تق": { kind: "text", tag: "h2", type: "text", label: "منصة وطنية لتسريع تبنّي تقنيات الزراعة والغذاء" },
  "t006-تأسّس-التحالف-السعودي-لتقن": { kind: "text", tag: "p", type: "long", label: "تأسّس التحالف السعودي لتقنيات الزراعة والغذاء كمنصّة وطنية للتعاون وال" },
  "t007-يُعدّ-التحالف-أحد-أبرز-مخر": { kind: "text", tag: "p", type: "long", label: "يُعدّ التحالف أحد أبرز مخرجات الخطة التنفيذية للبحث والابتكار في وزارة" },
  "i008-reelposter": { kind: "image", tag: "img", type: "image", label: "reel-poster.jpg" },
  "t009-شغّل-الفيديو": { kind: "text", tag: "span", type: "text", label: "شغّل الفيديو" },
  "t010-٢٠-ثانية-بلا-صوت": { kind: "text", tag: "span", type: "text", label: "٢٠ ثانية · بلا صوت" },
  "t011-قريبًا": { kind: "text", tag: "b", type: "text", label: "قريبًا" },
  "t012-Soon": { kind: "text", tag: "b", type: "text", label: "Soon" },
  "t013-قريبًا": { kind: "text", tag: "b", type: "text", label: "قريبًا" },
  "t014-Soon": { kind: "text", tag: "b", type: "text", label: "Soon" },
  "t015-نظرة-عامة": { kind: "text", tag: "h2", type: "text", label: "نظرة عامة" },
  "t016-مجموعة-عمل-مستهدفة": { kind: "text", tag: "p", type: "text", label: "مجموعة عمل مستهدفة" },
  "t017-أدوار-مؤسسية-أساسية": { kind: "text", tag: "p", type: "text", label: "أدوار مؤسسية أساسية" },
  "t018-قطاعات-ممثَّلة": { kind: "text", tag: "p", type: "text", label: "قطاعات ممثَّلة" },
  "t019-استراتيجيات-وطنية-متوائمة": { kind: "text", tag: "p", type: "text", label: "استراتيجيات وطنية متوائمة" },
  "t020-السياق-الوطني": { kind: "text", tag: "p", type: "text", label: "السياق الوطني" },
  "t021-تحديات-تجعل-الابتكار-ضرورة": { kind: "text", tag: "h2", type: "text", label: "تحديات تجعل الابتكار ضرورة" },
  "t022-تواجه-أنظمة-الزراعة-والغذا": { kind: "text", tag: "p", type: "long", label: "تواجه أنظمة الزراعة والغذاء في المملكة تحديات كبيرة، تخلق مجتمعةً دافع" },
  "t023-استعرض-مجموعات-العمل": { kind: "text", tag: "span", type: "text", label: "استعرض مجموعات العمل" },
  "i024-phclimate": { kind: "image", tag: "img", type: "image", label: "Harsh climate conditions" },
  "t025-قسوة-الظروف-المناخية": { kind: "text", tag: "h3", type: "text", label: "قسوة الظروف المناخية" },
  "t026-ارتفاع-درجات-الحرارة-ومحدو": { kind: "text", tag: "p", type: "text", label: "ارتفاع درجات الحرارة ومحدودية الأراضي الصالحة للزراعة يقيّدان ما يمكن " },
  "i027-phwaterscarcity": { kind: "image", tag: "img", type: "image", label: "Water scarcity" },
  "t028-شُح-الموارد-المائية": { kind: "text", tag: "h3", type: "text", label: "شُح الموارد المائية" },
  "t029-الزراعة-هي-أكبر-مستهلك-للم": { kind: "text", tag: "p", type: "long", label: "الزراعة هي أكبر مستهلك للمياه في المملكة، ما يجعل رفع الكفاءة أولوية و" },
  "i030-phpests": { kind: "image", tag: "img", type: "image", label: "Pest risks" },
  "t031-مخاطر-الآفات-الزراعية": { kind: "text", tag: "h3", type: "text", label: "مخاطر الآفات الزراعية" },
  "t032-خسائر-المحاصيل-بسبب-الآفات": { kind: "text", tag: "p", type: "text", label: "خسائر المحاصيل بسبب الآفات والأمراض تخفض الإنتاجية وترفع تكاليف المدخل" },
  "i033-phsoil": { kind: "image", tag: "img", type: "image", label: "Soil degradation" },
  "t034-تدهور-التربة": { kind: "text", tag: "h3", type: "text", label: "تدهور التربة" },
  "t035-الملوحة-وتراجع-المادة-العض": { kind: "text", tag: "p", type: "text", label: "الملوحة وتراجع المادة العضوية يقلّلان القدرة الإنتاجية للأراضي الزراعي" },
  "i036-phfoodwaste": { kind: "image", tag: "img", type: "image", label: "Food waste" },
  "t037-هدر-الغذاء": { kind: "text", tag: "h3", type: "text", label: "هدر الغذاء" },
  "t038-الفاقد-بين-الحصاد-والاستهل": { kind: "text", tag: "p", type: "text", label: "الفاقد بين الحصاد والاستهلاك يضعف العائد من كل لتر ماء مستخدم." },
  "t039-الأدوار-المؤسسية": { kind: "text", tag: "p", type: "text", label: "الأدوار المؤسسية" },
  "t040-أربعة-أدوار-توجّه-عمل-التح": { kind: "text", tag: "h2", type: "text", label: "أربعة أدوار توجّه عمل التحالف" },
  "t041-انبثق-التحالف-عن-الخطة-الت": { kind: "text", tag: "p", type: "long", label: "انبثق التحالف عن الخطة التنفيذية للبحث والابتكار بوزارة البيئة والمياه" },
  "t042-توجيه-الابتكار": { kind: "text", tag: "h3", type: "text", label: "توجيه الابتكار" },
  "t043-رصد-التقنيات-الناشئة-والمس": { kind: "text", tag: "p", type: "long", label: "رصد التقنيات الناشئة والمستقبلية، وتنسيق الجهود بين أصحاب المصلحة في ا" },
  "t044-بناء-الشراكات": { kind: "text", tag: "h3", type: "text", label: "بناء الشراكات" },
  "t045-إنشاء-وتعزيز-الروابط-بين-ا": { kind: "text", tag: "p", type: "long", label: "إنشاء وتعزيز الروابط بين الجهات الوطنية والدولية لتعظيم الاستفادة من ا" },
  "t046-تحفيز-الطلب-على-الابتكار": { kind: "text", tag: "h3", type: "text", label: "تحفيز الطلب على الابتكار" },
  "t047-تسهيل-تبنّي-التقنية-وإزالة": { kind: "text", tag: "p", type: "long", label: "تسهيل تبنّي التقنية وإزالة العوائق التنظيمية والنظامية التي تقف في طري" },
  "t048-تمكين-عرض-الابتكار": { kind: "text", tag: "h3", type: "text", label: "تمكين عرض الابتكار" },
  "t049-تمكين-الشركات-الناشئة-والم": { kind: "text", tag: "p", type: "long", label: "تمكين الشركات الناشئة والمبتكرين في قطاعات البيئة والمياه والزراعة، وت" },
  "i050-phmembership": { kind: "image", tag: "img", type: "image", label: "ph-membership.svg" },
  "t051-البيان-التأسيسي": { kind: "text", tag: "p", type: "text", label: "البيان التأسيسي" },
  "t052-يمثّل-تأسيسه-فرصة-تاريخية-": { kind: "text", tag: "h3", type: "long", label: "«يمثّل تأسيسه فرصة تاريخية لتسخير الذكاء الجماعي والقدرات المتنوعة وال" },
  "t053-تعرّف-على-المتحالفين": { kind: "text", tag: "span", type: "text", label: "تعرّف على المتحالفين" },
} as const satisfies FieldMap;

export const ABOUT_SECTIONS = [
  {
    key: "section-1",
    label: "ترويسة الصفحة",
    fields: ["t001-الرئيسية","t002-عن-التحالف","t003-منصة-وطنية-للتعاون-والتنسي"],
    cards: [

    ],
  },
  {
    key: "section-2",
    label: "من نحن",
    fields: ["t004-الرسالة-والرؤية","t005-منصة-وطنية-لتسريع-تبنّي-تق","t006-تأسّس-التحالف-السعودي-لتقن","t007-يُعدّ-التحالف-أحد-أبرز-مخر","i008-reelposter","t009-شغّل-الفيديو","t010-٢٠-ثانية-بلا-صوت"],
    cards: [

    ],
  },
  {
    key: "section-3",
    label: "رسالتنا ورؤيتنا",
    fields: ["t011-قريبًا","t012-Soon","t013-قريبًا","t014-Soon","t015-نظرة-عامة"],
    cards: [
      { key: "section-3::85", label: "مجموعة عمل مستهدفة", fields: ["t016-مجموعة-عمل-مستهدفة"] },
      { key: "section-3::88", label: "أدوار مؤسسية أساسية", fields: ["t017-أدوار-مؤسسية-أساسية"] },
      { key: "section-3::91", label: "قطاعات ممثَّلة", fields: ["t018-قطاعات-ممثَّلة"] },
      { key: "section-3::94", label: "استراتيجيات وطنية متوائمة", fields: ["t019-استراتيجيات-وطنية-متوائمة"] },
    ],
  },
  {
    key: "section-4",
    label: "ما نؤمن به",
    fields: ["t020-السياق-الوطني","t021-تحديات-تجعل-الابتكار-ضرورة","t022-تواجه-أنظمة-الزراعة-والغذا","t023-استعرض-مجموعات-العمل","i024-phclimate","t025-قسوة-الظروف-المناخية","t026-ارتفاع-درجات-الحرارة-ومحدو","i027-phwaterscarcity","t028-شُح-الموارد-المائية","t029-الزراعة-هي-أكبر-مستهلك-للم","i030-phpests","t031-مخاطر-الآفات-الزراعية","t032-خسائر-المحاصيل-بسبب-الآفات","i033-phsoil","t034-تدهور-التربة","t035-الملوحة-وتراجع-المادة-العض","i036-phfoodwaste","t037-هدر-الغذاء","t038-الفاقد-بين-الحصاد-والاستهل"],
    cards: [

    ],
  },
  {
    key: "section-5",
    label: "مسيرتنا",
    fields: ["t039-الأدوار-المؤسسية","t040-أربعة-أدوار-توجّه-عمل-التح","t041-انبثق-التحالف-عن-الخطة-الت"],
    cards: [
      { key: "section-5::143", label: "توجيه الابتكار", fields: ["t042-توجيه-الابتكار","t043-رصد-التقنيات-الناشئة-والمس"] },
      { key: "section-5::147", label: "بناء الشراكات", fields: ["t044-بناء-الشراكات","t045-إنشاء-وتعزيز-الروابط-بين-ا"] },
      { key: "section-5::151", label: "تحفيز الطلب على الابتكار", fields: ["t046-تحفيز-الطلب-على-الابتكار","t047-تسهيل-تبنّي-التقنية-وإزالة"] },
      { key: "section-5::155", label: "تمكين عرض الابتكار", fields: ["t048-تمكين-عرض-الابتكار","t049-تمكين-الشركات-الناشئة-والم"] },
    ],
  },
  {
    key: "section-6",
    label: "لافتة الانضمام",
    fields: ["i050-phmembership","t051-البيان-التأسيسي","t052-يمثّل-تأسيسه-فرصة-تاريخية-","t053-تعرّف-على-المتحالفين"],
    cards: [

    ],
  },
] as const;

const ABOUT_PAGE = {
  label: "عن التحالف",
  file: "about.html",
  apiBacked: true as const,
  fields: ABOUT_FIELDS,
  sections: ABOUT_SECTIONS,
};

export default ABOUT_PAGE;
