// GENERATED by `node scripts/generate-page-schema.mjs contact` from public/admin/schema.js
// + content/contact.json. Re-run after changing the admin's field/section layout for this
// page rather than hand-editing the field list below — the generator fails loudly if the
// two sources disagree, hand edits here can't.
import type { FieldMap } from './codec';

export const CONTACT_FIELDS = {
  "t001-الرئيسية": { kind: "text", tag: "a", type: "text", label: "الرئيسية" },
  "t002-تواصل-معنا": { kind: "text", tag: "h1", type: "text", label: "تواصل معنا" },
  "t003-للاستفسارات-وفرص-الشراكة-و": { kind: "text", tag: "p", type: "text", label: "للاستفسارات وفرص الشراكة وطلبات الدعم، تواصل معنا." },
  "t059-إرسال": { kind: "text", tag: "span", type: "text", label: "إرسال" },
  "t060-تم-استلام-طلبك-سنتواصل-معك": { kind: "text", tag: "span", type: "text", label: "تم استلام طلبك. سنتواصل معك قريبًا." },
  "t004-الاسم-الكامل": { kind: "text", tag: "label", type: "rich", label: "الاسم الكامل" },
  "p005-مثال-سارة-الأحمد": { kind: "text", tag: "placeholder", type: "text", label: "نص إرشادي: مثال: سارة الأحمد" },
  "t006-البريد-الإلكتروني": { kind: "text", tag: "label", type: "rich", label: "البريد الإلكتروني" },
  "p007-namecompanycom": { kind: "text", tag: "placeholder", type: "text", label: "نص إرشادي: name@company.com" },
  "t008-رقم-الجوال": { kind: "text", tag: "label", type: "rich", label: "رقم الجوال" },
  "t009-أضف-رمز-الدولة-مثال-96659x": { kind: "text", tag: "p", type: "text", label: "أضف رمز الدولة. مثال: ‎+96659xxxxxxx" },
  "p010-966": { kind: "text", tag: "placeholder", type: "text", label: "نص إرشادي: ‎+966" },
  "t011-اسم-الجهة-أو-الشركة": { kind: "text", tag: "label", type: "rich", label: "اسم الجهة أو الشركة" },
  "p012-مثال-الكثبان-الخضراء": { kind: "text", tag: "placeholder", type: "text", label: "نص إرشادي: مثال: الكثبان الخضراء" },
  "t013-القطاع": { kind: "text", tag: "label", type: "rich", label: "القطاع" },
  "t014-الرجاء-الاختيار": { kind: "text", tag: "option", type: "text", label: "الرجاء الاختيار" },
  "t015-تقنيات-الزراعة": { kind: "text", tag: "option", type: "text", label: "تقنيات الزراعة" },
  "t016-تقنيات-الأغذية": { kind: "text", tag: "option", type: "text", label: "تقنيات الأغذية" },
  "t017-المياه-والري": { kind: "text", tag: "option", type: "text", label: "المياه والري" },
  "t018-الزراعة-البيئية-المحكومة": { kind: "text", tag: "option", type: "text", label: "الزراعة البيئية المحكومة" },
  "t019-البروتين-البديل": { kind: "text", tag: "option", type: "text", label: "البروتين البديل" },
  "t020-سلاسل-الإمداد-والخدمات-الل": { kind: "text", tag: "option", type: "text", label: "سلاسل الإمداد والخدمات اللوجستية" },
  "t021-التقنية-الحيوية": { kind: "text", tag: "option", type: "text", label: "التقنية الحيوية" },
  "t022-الطاقة-المتجددة": { kind: "text", tag: "option", type: "text", label: "الطاقة المتجددة" },
  "t023-البيانات-والذكاء-الاصطناعي": { kind: "text", tag: "option", type: "text", label: "البيانات والذكاء الاصطناعي" },
  "t024-البحث-والأوساط-الأكاديمية": { kind: "text", tag: "option", type: "text", label: "البحث والأوساط الأكاديمية" },
  "t025-الجهات-الحكومية-والسياسات": { kind: "text", tag: "option", type: "text", label: "الجهات الحكومية والسياسات" },
  "t026-الاستثمار-والتمويل": { kind: "text", tag: "option", type: "text", label: "الاستثمار والتمويل" },
  "t027-غير-ربحي": { kind: "text", tag: "option", type: "text", label: "غير ربحي" },
  "t028-أخرى": { kind: "text", tag: "option", type: "text", label: "أخرى" },
  "t032-الدولة": { kind: "text", tag: "label", type: "rich", label: "الدولة" },
  "t033-الرجاء-الاختيار": { kind: "text", tag: "option", type: "text", label: "الرجاء الاختيار" },
  "t034-المملكة-العربية-السعودية": { kind: "text", tag: "option", type: "text", label: "المملكة العربية السعودية" },
  "t035-الإمارات-العربية-المتحدة": { kind: "text", tag: "option", type: "text", label: "الإمارات العربية المتحدة" },
  "t036-الكويت": { kind: "text", tag: "option", type: "text", label: "الكويت" },
  "t037-قطر": { kind: "text", tag: "option", type: "text", label: "قطر" },
  "t038-البحرين": { kind: "text", tag: "option", type: "text", label: "البحرين" },
  "t039-عُمان": { kind: "text", tag: "option", type: "text", label: "عُمان" },
  "t040-مصر": { kind: "text", tag: "option", type: "text", label: "مصر" },
  "t041-الأردن": { kind: "text", tag: "option", type: "text", label: "الأردن" },
  "t042-هولندا": { kind: "text", tag: "option", type: "text", label: "هولندا" },
  "t043-المملكة-المتحدة": { kind: "text", tag: "option", type: "text", label: "المملكة المتحدة" },
  "t044-الولايات-المتحدة": { kind: "text", tag: "option", type: "text", label: "الولايات المتحدة" },
  "t045-ألمانيا": { kind: "text", tag: "option", type: "text", label: "ألمانيا" },
  "t046-فرنسا": { kind: "text", tag: "option", type: "text", label: "فرنسا" },
  "t047-الصين": { kind: "text", tag: "option", type: "text", label: "الصين" },
  "t048-اليابان": { kind: "text", tag: "option", type: "text", label: "اليابان" },
  "t049-الهند": { kind: "text", tag: "option", type: "text", label: "الهند" },
  "t050-أستراليا": { kind: "text", tag: "option", type: "text", label: "أستراليا" },
  "t051-دولة-أخرى": { kind: "text", tag: "option", type: "text", label: "دولة أخرى" },
  "t061-التواصل-المباشر": { kind: "text", tag: "h3", type: "text", label: "التواصل المباشر" },
  "t062-اختر-القناة-الأنسب-لطلبك-أ": { kind: "text", tag: "p", type: "text", label: "اختر القناة الأنسب لطلبك — أو استخدم النموذج وسنوجّهه للجهة الصحيحة." },
  "t063-الاستفسارات-العامة-والدعم": { kind: "text", tag: "b", type: "text", label: "الاستفسارات العامة والدعم" },
  "t064-العضوية": { kind: "text", tag: "b", type: "text", label: "العضوية" },
  "t065-سجّل-اهتمامك-بالانضمام": { kind: "text", tag: "a", type: "text", label: "سجّل اهتمامك بالانضمام" },
  "t066-الاستفسارات-الإعلامية": { kind: "text", tag: "b", type: "text", label: "الاستفسارات الإعلامية" },
  "t067-المركز-الإعلامي": { kind: "text", tag: "a", type: "text", label: "المركز الإعلامي" },
  "t068-مدة-الرد": { kind: "text", tag: "b", type: "text", label: "مدة الرد" },
  "t069-ثلاثة-أيام-عمل-في-المتوسط": { kind: "text", tag: "span", type: "text", label: "ثلاثة أيام عمل في المتوسط." },
  "t070-تابعنا": { kind: "text", tag: "p", type: "text", label: "تابعنا" },
} as const satisfies FieldMap;

export const CONTACT_SECTIONS = [
  {
    key: "section-1",
    label: "ترويسة الصفحة",
    fields: ["t001-الرئيسية","t002-تواصل-معنا","t003-للاستفسارات-وفرص-الشراكة-و"],
    cards: [

    ],
  },
  {
    key: "contactMain",
    label: "نموذج التواصل وبيانات الاتصال",
    fields: ["t059-إرسال","t060-تم-استلام-طلبك-سنتواصل-معك"],
    cards: [
      { key: "contactMain::59", label: "الاسم الكامل", fields: ["t004-الاسم-الكامل","p005-مثال-سارة-الأحمد"] },
      { key: "contactMain::64", label: "البريد الإلكتروني", fields: ["t006-البريد-الإلكتروني","p007-namecompanycom"] },
      { key: "contactMain::68", label: "رقم الجوال", fields: ["t008-رقم-الجوال","t009-أضف-رمز-الدولة-مثال-96659x","p010-966"] },
      { key: "contactMain::74", label: "اسم الجهة أو الشركة", fields: ["t011-اسم-الجهة-أو-الشركة","p012-مثال-الكثبان-الخضراء"] },
      { key: "contactMain::78", label: "القطاع", fields: ["t013-القطاع","t014-الرجاء-الاختيار","t015-تقنيات-الزراعة","t016-تقنيات-الأغذية","t017-المياه-والري","t018-الزراعة-البيئية-المحكومة","t019-البروتين-البديل","t020-سلاسل-الإمداد-والخدمات-الل","t021-التقنية-الحيوية","t022-الطاقة-المتجددة","t023-البيانات-والذكاء-الاصطناعي","t024-البحث-والأوساط-الأكاديمية","t025-الجهات-الحكومية-والسياسات","t026-الاستثمار-والتمويل","t027-غير-ربحي","t028-أخرى"] },
      { key: "contactMain::103", label: "الدولة", fields: ["t032-الدولة","t033-الرجاء-الاختيار","t034-المملكة-العربية-السعودية","t035-الإمارات-العربية-المتحدة","t036-الكويت","t037-قطر","t038-البحرين","t039-عُمان","t040-مصر","t041-الأردن","t042-هولندا","t043-المملكة-المتحدة","t044-الولايات-المتحدة","t045-ألمانيا","t046-فرنسا","t047-الصين","t048-اليابان","t049-الهند","t050-أستراليا","t051-دولة-أخرى"] },
      { key: "contactMain::151", label: "التواصل المباشر", fields: ["t061-التواصل-المباشر","t062-اختر-القناة-الأنسب-لطلبك-أ","t063-الاستفسارات-العامة-والدعم","t064-العضوية","t065-سجّل-اهتمامك-بالانضمام","t066-الاستفسارات-الإعلامية","t067-المركز-الإعلامي","t068-مدة-الرد","t069-ثلاثة-أيام-عمل-في-المتوسط","t070-تابعنا"] },
    ],
  },
] as const;

const CONTACT_PAGE = {
  label: "تواصل معنا",
  file: "contact.html",
  apiBacked: true as const,
  fields: CONTACT_FIELDS,
  sections: CONTACT_SECTIONS,
};

export default CONTACT_PAGE;
