// GENERATED by `node scripts/generate-page-schema.mjs index` from public/admin/schema.js
// + content/index.json. Re-run after changing the admin's field/section layout for this
// page rather than hand-editing the field list below — the generator fails loudly if the
// two sources disagree, hand edits here can't.
import type { FieldMap } from './codec';

export const INDEX_FIELDS = {
  "i001-gd02bedshero": { kind: "image", tag: "img", type: "image", label: "gd-02-beds-hero.webp" },
  "i002-gd03rowshero": { kind: "image", tag: "img", type: "image", label: "gd-03-rows-hero.webp" },
  "i003-gd09rackshero": { kind: "image", tag: "img", type: "image", label: "gd-09-racks-hero.webp" },
  "t004-رؤى-سافتا": { kind: "text", tag: "p", type: "text", label: "رؤى سافتا" },
  "t005-معرفة-تطبيقية-تدعم-قرارات-": { kind: "text", tag: "h1", type: "long", label: "معرفة تطبيقية تدعم قرارات تبنّي تقنيات الزراعة والغذاء في المملكة." },
  "t006-استعرض-الرؤى": { kind: "text", tag: "span", type: "text", label: "استعرض الرؤى" },
  "t007-الشراكات": { kind: "text", tag: "p", type: "text", label: "الشراكات" },
  "t008-الجهات-الحكومية-والبحثية-و": { kind: "text", tag: "h2", type: "text", label: "الجهات الحكومية والبحثية والقطاع الخاص — تحالف واحد." },
  "t009-تعرّف-على-المتحالفين": { kind: "text", tag: "span", type: "text", label: "تعرّف على المتحالفين" },
  "t010-الإعلانات": { kind: "text", tag: "p", type: "text", label: "الإعلانات" },
  "t011-التحالف-يفتح-باب-العضوية-ف": { kind: "text", tag: "h2", type: "long", label: "التحالف يفتح باب العضوية في مجموعات عمله للجهات المهتمة بتقنيات الزراع" },
  "t012-سجّل-اهتمامك": { kind: "text", tag: "span", type: "text", label: "سجّل اهتمامك" },
  "t013-رؤى-سافتا": { kind: "text", tag: "span", type: "text", label: "رؤى سافتا" },
  "t014-الشراكات": { kind: "text", tag: "span", type: "text", label: "الشراكات" },
  "t015-الإعلانات": { kind: "text", tag: "span", type: "text", label: "الإعلانات" },
  "t016-تعرّف-على-التحالف": { kind: "text", tag: "p", type: "text", label: "تعرّف على التحالف" },
  "t017-نحن-التحالف-الوطني-السعودي": { kind: "text", tag: "h2", type: "long", label: "نحن التحالف الوطني السعودي لتقنيات الزراعة والغذاء — نجمع الجهات الحكو" },
  "i018-kaust1thumb": { kind: "image", tag: "img", type: "image", label: "Open raceway ponds for algae cultivation at KAUST" },
  "t019-مجموعات-العمل": { kind: "text", tag: "p", type: "text", label: "مجموعات العمل" },
  "t020-9-مجموعات-عمل-تعالج-تحديات": { kind: "text", tag: "h3", type: "text", label: "9 مجموعات عمل تعالج تحديات الزراعة والغذاء في المملكة" },
  "i021-kaust4thumb": { kind: "image", tag: "img", type: "image", label: "What we do" },
  "t022-ما-نقوم-به": { kind: "text", tag: "p", type: "text", label: "ما نقوم به" },
  "t023-من-الري-الذكي-إلى-خفض-الفا": { kind: "text", tag: "h3", type: "text", label: "من الري الذكي إلى خفض الفاقد الغذائي — الابتكار هو المفتاح" },
  "t024-التحديات": { kind: "text", tag: "p", type: "text", label: "التحديات" },
  "t025-خمسة-تحديات-وطنية-تُوجّه-ع": { kind: "text", tag: "h2", type: "long", label: "خمسة تحديات وطنية تُوجّه عمل التحالف وأولوياته في تبنّي تقنيات الزراعة" },
  "i026-phwaterscarcity": { kind: "image", tag: "img", type: "image", label: "Water scarcity" },
  "t027-شُح-الموارد-المائية": { kind: "text", tag: "h4", type: "text", label: "شُح الموارد المائية" },
  "i029-phclimate": { kind: "image", tag: "img", type: "image", label: "Harsh climate conditions" },
  "t030-قسوة-الظروف-المناخية": { kind: "text", tag: "h4", type: "text", label: "قسوة الظروف المناخية" },
  "i032-phpests": { kind: "image", tag: "img", type: "image", label: "Pest risks" },
  "t033-مخاطر-الآفات-الزراعية": { kind: "text", tag: "h4", type: "text", label: "مخاطر الآفات الزراعية" },
  "i035-phsoil": { kind: "image", tag: "img", type: "image", label: "Soil degradation" },
  "t036-تدهور-التربة": { kind: "text", tag: "h4", type: "text", label: "تدهور التربة" },
  "i038-phfoodwaste": { kind: "image", tag: "img", type: "image", label: "Food waste" },
  "t039-هدر-الغذاء": { kind: "text", tag: "h4", type: "text", label: "هدر الغذاء" },
  "i061-phimportdependency": { kind: "image", tag: "img", type: "image", label: "Import dependency and food security exposure" },
  "t062-الاعتماد-على-الاستيراد": { kind: "text", tag: "h4", type: "text", label: "الاعتماد على الاستيراد وانكشاف الأمن الغذائي" },
  "i063-phtechgaps": { kind: "image", tag: "img", type: "image", label: "Technology and extension gaps" },
  "t064-فجوات-التقنية-والإرشاد": { kind: "text", tag: "h4", type: "text", label: "فجوات التقنية والإرشاد الزراعي" },
  "t041-قريبًا": { kind: "text", tag: "b", type: "text", label: "قريبًا" },
  "t045-التميّز": { kind: "text", tag: "p", type: "text", label: "التميّز" },
  "t046-جوائز-سافتا-للتميّز": { kind: "text", tag: "h2", type: "text", label: "جوائز سافتا للتميّز" },
  "t047-جائزة-سنوية-تكرّم-الجهات-و": { kind: "text", tag: "p", type: "long", label: "جائزة سنوية تكرّم الجهات والفرق التي حقّقت أثرًا ملموسًا في تقنيات الز" },
  "t048-سجّل-اهتمامك-بالترشّح": { kind: "text", tag: "span", type: "text", label: "سجّل اهتمامك بالترشّح" },
  "t049-ابتكار-العام": { kind: "text", tag: "h3", type: "text", label: "ابتكار العام" },
  "t050-حل-تقني-أثبت-أثره-في-الإنت": { kind: "text", tag: "p", type: "text", label: "حل تقني أثبت أثره في الإنتاجية أو كفاءة الموارد." },
  "t051-كفاءة-الموارد-المائية": { kind: "text", tag: "h3", type: "text", label: "كفاءة الموارد المائية" },
  "t052-أفضل-خفض-موثّق-في-استهلاك-": { kind: "text", tag: "p", type: "text", label: "أفضل خفض موثّق في استهلاك مياه الري." },
  "t053-مجموعة-العمل-المتميزة": { kind: "text", tag: "h3", type: "text", label: "مجموعة العمل المتميزة" },
  "t054-المجموعة-الأعلى-إنتاجية-في": { kind: "text", tag: "p", type: "text", label: "المجموعة الأعلى إنتاجية في مخرجاتها البحثية والتطبيقية." },
  "t055-الشركة-الناشئة-الواعدة": { kind: "text", tag: "h3", type: "text", label: "الشركة الناشئة الواعدة" },
  "t056-شركة-ناشئة-سعودية-ذات-حل-ق": { kind: "text", tag: "p", type: "text", label: "شركة ناشئة سعودية ذات حل قابل للتوسّع." },
  "t057-أثر-الكوادر-الوطنية": { kind: "text", tag: "h3", type: "text", label: "أثر الكوادر الوطنية" },
  "t058-برنامج-بنى-قدرات-وطنية-في-": { kind: "text", tag: "p", type: "text", label: "برنامج بنى قدرات وطنية في القطاع." },
} as const satisfies FieldMap;

export const INDEX_SECTIONS = [
  {
    key: "hero",
    label: "الهيرو — الشرائح الثلاث",
    fields: ["i001-gd02bedshero","i002-gd03rowshero","i003-gd09rackshero","t004-رؤى-سافتا","t005-معرفة-تطبيقية-تدعم-قرارات-","t006-استعرض-الرؤى","t007-الشراكات","t008-الجهات-الحكومية-والبحثية-و","t009-تعرّف-على-المتحالفين","t010-الإعلانات","t011-التحالف-يفتح-باب-العضوية-ف","t012-سجّل-اهتمامك","t013-رؤى-سافتا","t014-الشراكات","t015-الإعلانات"],
    cards: [

    ],
  },
  {
    key: "section-2",
    label: "تعرّف على التحالف",
    fields: ["t016-تعرّف-على-التحالف","t017-نحن-التحالف-الوطني-السعودي"],
    cards: [
      { key: "section-2::103", label: "9 مجموعات عمل تعالج تحديات الزراعة والغذاء في المملكة", fields: ["i018-kaust1thumb","t019-مجموعات-العمل","t020-9-مجموعات-عمل-تعالج-تحديات"] },
      { key: "section-2::111", label: "من الري الذكي إلى خفض الفاقد الغذائي — الابتكار هو المفتاح", fields: ["i021-kaust4thumb","t022-ما-نقوم-به","t023-من-الري-الذكي-إلى-خفض-الفا"] },
    ],
  },
  {
    key: "challenges",
    label: "التحديات الوطنية",
    fields: ["t024-التحديات","t025-خمسة-تحديات-وطنية-تُوجّه-ع"],
    cards: [
      { key: "challenges::133", label: "شُح الموارد المائية", fields: ["i026-phwaterscarcity","t027-شُح-الموارد-المائية"] },
      { key: "challenges::141", label: "قسوة الظروف المناخية", fields: ["i029-phclimate","t030-قسوة-الظروف-المناخية"] },
      { key: "challenges::149", label: "مخاطر الآفات الزراعية", fields: ["i032-phpests","t033-مخاطر-الآفات-الزراعية"] },
      { key: "challenges::157", label: "تدهور التربة", fields: ["i035-phsoil","t036-تدهور-التربة"] },
      { key: "challenges::165", label: "هدر الغذاء", fields: ["i038-phfoodwaste","t039-هدر-الغذاء"] },
      { key: "challenges::142", label: "الاعتماد على الاستيراد وانكشاف الأمن الغذائي", fields: ["i061-phimportdependency","t062-الاعتماد-على-الاستيراد"] },
      { key: "challenges::146", label: "فجوات التقنية والإرشاد الزراعي", fields: ["i063-phtechgaps","t064-فجوات-التقنية-والإرشاد"] },
    ],
  },
  {
    key: "awards",
    label: "جوائز التميّز",
    fields: ["t041-قريبًا","t045-التميّز","t046-جوائز-سافتا-للتميّز","t047-جائزة-سنوية-تكرّم-الجهات-و","t048-سجّل-اهتمامك-بالترشّح","t049-ابتكار-العام","t050-حل-تقني-أثبت-أثره-في-الإنت","t051-كفاءة-الموارد-المائية","t052-أفضل-خفض-موثّق-في-استهلاك-","t053-مجموعة-العمل-المتميزة","t054-المجموعة-الأعلى-إنتاجية-في","t055-الشركة-الناشئة-الواعدة","t056-شركة-ناشئة-سعودية-ذات-حل-ق","t057-أثر-الكوادر-الوطنية","t058-برنامج-بنى-قدرات-وطنية-في-"],
    cards: [

    ],
  },
] as const;

const INDEX_PAGE = {
  label: "الصفحة الرئيسية",
  file: "index.html",
  apiBacked: true as const,
  fields: INDEX_FIELDS,
  sections: INDEX_SECTIONS,
};

export default INDEX_PAGE;
