// GENERATED by `node scripts/generate-page-schema.mjs media` from public/admin/schema.js
// + content/media.json. Re-run after changing the admin's field/section layout for this
// page rather than hand-editing the field list below — the generator fails loudly if the
// two sources disagree, hand edits here can't.
import type { FieldMap } from './codec';

export const MEDIA_FIELDS = {
  "t001-الرئيسية": { kind: "text", tag: "a", type: "text", label: "الرئيسية" },
  "t002-المركز-الإعلامي": { kind: "text", tag: "h1", type: "text", label: "المركز الإعلامي" },
  "t003-الأخبار-والرؤى-والصور-والف": { kind: "text", tag: "p", type: "text", label: "الأخبار والرؤى والصور والفعاليات من مختلف أنشطة التحالف." },
  "t004-بيانات-تجريبية-المدخلات-في": { kind: "text", tag: "span", type: "rich", label: "بيانات تجريبية. المدخلات في هذه الصفحة عناصر مبدئية لعرض التصميم فقط، " },
  "i005-phnews": { kind: "image", tag: "img", type: "image", label: "ph-news.svg" },
  "t006-أخبار-28-يوليو-2026": { kind: "text", tag: "p", type: "text", label: "أخبار · 28 يوليو 2026" },
  "t007-التحالف-ووزارة-البيئة-والم": { kind: "text", tag: "h3", type: "text", label: "التحالف ووزارة البيئة والمياه والزراعة يوقّعان مذكرة لتسريع تقنيات الز" },
  "i008-phmembership": { kind: "image", tag: "img", type: "image", label: "ph-membership.svg" },
  "t009-أخبار-14-يوليو-2026": { kind: "text", tag: "p", type: "text", label: "أخبار · 14 يوليو 2026" },
  "t010-انعقاد-الدفعة-الأولى-من-مج": { kind: "text", tag: "h3", type: "text", label: "انعقاد الدفعة الأولى من مجموعات العمل في الرياض لوضع الأجندة البحثية" },
  "i011-phinsight02": { kind: "image", tag: "img", type: "image", label: "ph-insight-02.svg" },
  "t012-أخبار-30-يونيو-2026": { kind: "text", tag: "p", type: "text", label: "أخبار · 30 يونيو 2026" },
  "t013-التحالف-ينشر-خطاب-الاهتمام": { kind: "text", tag: "h3", type: "text", label: "التحالف ينشر خطاب الاهتمام بالعضوية لعام 2026" },
  "i014-phwhatwedo": { kind: "image", tag: "img", type: "image", label: "ph-what-we-do.svg" },
  "t015-أخبار-09-يونيو-2026": { kind: "text", tag: "p", type: "text", label: "أخبار · 09 يونيو 2026" },
  "t016-التحالف-يشارك-مراكز-بحثية-": { kind: "text", tag: "h3", type: "text", label: "التحالف يشارك مراكز بحثية وطنية في تجارب الزراعة الدقيقة" },
} as const satisfies FieldMap;

export const MEDIA_SECTIONS = [
  {
    key: "section-1",
    label: "ترويسة الصفحة",
    fields: ["t001-الرئيسية","t002-المركز-الإعلامي","t003-الأخبار-والرؤى-والصور-والف"],
    cards: [

    ],
  },
  {
    key: "section-2",
    label: "الأخبار والرؤى والفعاليات",
    fields: [],
    cards: [
      { key: "section-2::57", label: "<b>بيانات تجريبية.</b> المدخلات في هذه الصفحة عناصر مبدئية ل", fields: ["t004-بيانات-تجريبية-المدخلات-في"] },
      { key: "section-2::65", label: "التحالف ووزارة البيئة والمياه والزراعة يوقّعان مذكرة لتسريع ", fields: ["i005-phnews","t006-أخبار-28-يوليو-2026","t007-التحالف-ووزارة-البيئة-والم"] },
      { key: "section-2::75", label: "انعقاد الدفعة الأولى من مجموعات العمل في الرياض لوضع الأجندة", fields: ["i008-phmembership","t009-أخبار-14-يوليو-2026","t010-انعقاد-الدفعة-الأولى-من-مج"] },
      { key: "section-2::85", label: "التحالف ينشر خطاب الاهتمام بالعضوية لعام 2026", fields: ["i011-phinsight02","t012-أخبار-30-يونيو-2026","t013-التحالف-ينشر-خطاب-الاهتمام"] },
      { key: "section-2::95", label: "التحالف يشارك مراكز بحثية وطنية في تجارب الزراعة الدقيقة", fields: ["i014-phwhatwedo","t015-أخبار-09-يونيو-2026","t016-التحالف-يشارك-مراكز-بحثية-"] },
    ],
  },
] as const;

const MEDIA_PAGE = {
  label: "المركز الإعلامي",
  file: "media.html",
  apiBacked: true as const,
  fields: MEDIA_FIELDS,
  sections: MEDIA_SECTIONS,
};

export default MEDIA_PAGE;
