// GENERATED by `node scripts/generate-page-schema.mjs register-interest` from public/admin/schema.js
// + content/register-interest.json. Re-run after changing the admin's field/section layout for this
// page rather than hand-editing the field list below — the generator fails loudly if the
// two sources disagree, hand edits here can't.
import type { FieldMap } from './codec';

export const REGISTER_INTEREST_FIELDS = {
  "t001-الرئيسية": { kind: "text", tag: "a", type: "text", label: "الرئيسية" },
  "t002-سجّل-اهتمامك": { kind: "text", tag: "h1", type: "text", label: "سجّل اهتمامك" },
  "t003-عرّفنا-بجهتك-والتحدي-الذي-": { kind: "text", tag: "p", type: "long", label: "عرّفنا بجهتك والتحدي الذي ترغب بالعمل عليه، وسنتواصل معك بحزمة العضوية" },
  "t031-أُقرّ-بأنني-مخوّل-بتقديم-ه": { kind: "text", tag: "span", type: "rich", label: "أُقرّ بأنني مخوّل بتقديم هذا الطلب نيابةً عن الجهة المذكورة أعلاه، وأو" },
  "t032-إرسال-التسجيل": { kind: "text", tag: "span", type: "text", label: "إرسال التسجيل" },
  "t033-شكرًا-لك-تم-تسجيل-طلبك-بنج": { kind: "text", tag: "span", type: "text", label: "شكرًا لك — تم تسجيل طلبك بنجاح." },
  "t004-الاسم-الكامل": { kind: "text", tag: "label", type: "text", label: "الاسم الكامل *" },
  "t005-اسم-الجهة": { kind: "text", tag: "label", type: "text", label: "اسم الجهة *" },
  "t006-نوع-الجهة": { kind: "text", tag: "label", type: "text", label: "نوع الجهة *" },
  "t007-اختر": { kind: "text", tag: "option", type: "text", label: "اختر…" },
  "t008-جهة-حكومية": { kind: "text", tag: "option", type: "text", label: "جهة حكومية" },
  "t009-مؤسسة-أكاديمية": { kind: "text", tag: "option", type: "text", label: "مؤسسة أكاديمية" },
  "t010-شركة-من-القطاع-الخاص": { kind: "text", tag: "option", type: "text", label: "شركة من القطاع الخاص" },
  "t011-منظمة-غير-ربحية": { kind: "text", tag: "option", type: "text", label: "منظمة غير ربحية" },
  "t012-مبتكر-فرد": { kind: "text", tag: "option", type: "text", label: "مبتكر فرد" },
  "t013-البريد-الإلكتروني-للعمل": { kind: "text", tag: "label", type: "text", label: "البريد الإلكتروني للعمل *" },
  "t014-رقم-الجوال": { kind: "text", tag: "label", type: "text", label: "رقم الجوال" },
  "t015-الموقع-الإلكتروني": { kind: "text", tag: "label", type: "text", label: "الموقع الإلكتروني" },
  "p016-https": { kind: "text", tag: "placeholder", type: "text", label: "نص إرشادي: https://" },
  "t017-مجال-الاهتمام": { kind: "text", tag: "label", type: "text", label: "مجال الاهتمام *" },
  "t018-اختر": { kind: "text", tag: "option", type: "text", label: "اختر…" },
  "t019-قسوة-الظروف-المناخية": { kind: "text", tag: "option", type: "text", label: "قسوة الظروف المناخية" },
  "t020-شُح-الموارد-المائية": { kind: "text", tag: "option", type: "text", label: "شُح الموارد المائية" },
  "t021-مخاطر-الآفات-الزراعية": { kind: "text", tag: "option", type: "text", label: "مخاطر الآفات الزراعية" },
  "t022-تدهور-التربة": { kind: "text", tag: "option", type: "text", label: "تدهور التربة" },
  "t023-هدر-الغذاء": { kind: "text", tag: "option", type: "text", label: "هدر الغذاء" },
  "t024-أخرى-غير-محدد-بعد": { kind: "text", tag: "option", type: "text", label: "أخرى / غير محدد بعد" },
  "t025-مرتبط-بالتحديات-الوطنية-ال": { kind: "text", tag: "p", type: "text", label: "مرتبط بالتحديات الوطنية الخمسة التي يعمل عليها التحالف." },
  "t026-لماذا-ترغب-بالانضمام؟": { kind: "text", tag: "label", type: "text", label: "لماذا ترغب بالانضمام؟" },
  "t027-ملف-الأعمال-أو-العرض-التعر": { kind: "text", tag: "label", type: "text", label: "ملف الأعمال أو العرض التعريفي" },
  "t028-PDF-أو-PPTX-أو-DOCX-حتى-10": { kind: "text", tag: "p", type: "text", label: "PDF أو PPTX أو DOCX · حتى 10 م.ب · اختياري" },
  "t029-اختر-ملفًا": { kind: "text", tag: "label", type: "text", label: "اختر ملفًا" },
  "t030-لم-يُختر-أي-ملف": { kind: "text", tag: "span", type: "text", label: "لم يُختر أي ملف" },
  "t034-ماذا-بعد؟": { kind: "text", tag: "h3", type: "text", label: "ماذا بعد؟" },
  "t035-أربع-خطوات-من-إرسال-الطلب-": { kind: "text", tag: "p", type: "text", label: "أربع خطوات من إرسال الطلب حتى إدراج جهتك في دليل المتحالفين." },
  "t036-المراجعة": { kind: "text", tag: "b", type: "text", label: "المراجعة" },
  "t037-يراجع-فريق-التحالف-طلبك-وي": { kind: "text", tag: "span", type: "text", label: "يراجع فريق التحالف طلبك ويتحقّق من اكتمال بياناته." },
  "t038-التواصل": { kind: "text", tag: "b", type: "text", label: "التواصل" },
  "t039-نتواصل-معك-عبر-البريد-الإل": { kind: "text", tag: "span", type: "text", label: "نتواصل معك عبر البريد الإلكتروني الذي زوّدتنا به." },
  "t040-خطاب-العضوية": { kind: "text", tag: "b", type: "text", label: "خطاب العضوية" },
  "t041-تتلقّى-الجهات-المؤهّلة-خطا": { kind: "text", tag: "span", type: "text", label: "تتلقّى الجهات المؤهّلة خطاب الاهتمام بالعضوية للتوقيع." },
  "t042-الإدراج": { kind: "text", tag: "b", type: "text", label: "الإدراج" },
  "t043-بعد-التوقيع-تُدرَج-جهتك-في": { kind: "text", tag: "span", type: "text", label: "بعد التوقيع تُدرَج جهتك في دليل المتحالفين على الموقع." },
  "t044-عندك-سؤال؟": { kind: "text", tag: "p", type: "text", label: "عندك سؤال؟" },
} as const satisfies FieldMap;

export const REGISTER_INTEREST_SECTIONS = [
  {
    key: "section-1",
    label: "ترويسة الصفحة",
    fields: ["t001-الرئيسية","t002-سجّل-اهتمامك","t003-عرّفنا-بجهتك-والتحدي-الذي-"],
    cards: [

    ],
  },
  {
    key: "section-2",
    label: "نموذج تسجيل الاهتمام",
    fields: ["t031-أُقرّ-بأنني-مخوّل-بتقديم-ه","t032-إرسال-التسجيل","t033-شكرًا-لك-تم-تسجيل-طلبك-بنج"],
    cards: [
      { key: "section-2::60", label: "الاسم الكامل *", fields: ["t004-الاسم-الكامل"] },
      { key: "section-2::63", label: "اسم الجهة *", fields: ["t005-اسم-الجهة"] },
      { key: "section-2::67", label: "نوع الجهة *", fields: ["t006-نوع-الجهة","t007-اختر","t008-جهة-حكومية","t009-مؤسسة-أكاديمية","t010-شركة-من-القطاع-الخاص","t011-منظمة-غير-ربحية","t012-مبتكر-فرد"] },
      { key: "section-2::76", label: "البريد الإلكتروني للعمل *", fields: ["t013-البريد-الإلكتروني-للعمل"] },
      { key: "section-2::80", label: "رقم الجوال", fields: ["t014-رقم-الجوال"] },
      { key: "section-2::83", label: "الموقع الإلكتروني", fields: ["t015-الموقع-الإلكتروني","p016-https"] },
      { key: "section-2::86", label: "مجال الاهتمام *", fields: ["t017-مجال-الاهتمام","t018-اختر","t019-قسوة-الظروف-المناخية","t020-شُح-الموارد-المائية","t021-مخاطر-الآفات-الزراعية","t022-تدهور-التربة","t023-هدر-الغذاء","t024-أخرى-غير-محدد-بعد","t025-مرتبط-بالتحديات-الوطنية-ال"] },
      { key: "section-2::97", label: "لماذا ترغب بالانضمام؟", fields: ["t026-لماذا-ترغب-بالانضمام؟"] },
      { key: "section-2::100", label: "لم يُختر أي ملف", fields: ["t027-ملف-الأعمال-أو-العرض-التعر","t028-PDF-أو-PPTX-أو-DOCX-حتى-10","t029-اختر-ملفًا","t030-لم-يُختر-أي-ملف"] },
      { key: "section-2::121", label: "ماذا بعد؟", fields: ["t034-ماذا-بعد؟","t035-أربع-خطوات-من-إرسال-الطلب-","t036-المراجعة","t037-يراجع-فريق-التحالف-طلبك-وي","t038-التواصل","t039-نتواصل-معك-عبر-البريد-الإل","t040-خطاب-العضوية","t041-تتلقّى-الجهات-المؤهّلة-خطا","t042-الإدراج","t043-بعد-التوقيع-تُدرَج-جهتك-في","t044-عندك-سؤال؟"] },
    ],
  },
] as const;

const REGISTER_INTEREST_PAGE = {
  label: "سجّل اهتمامك",
  file: "register-interest.html",
  apiBacked: true as const,
  fields: REGISTER_INTEREST_FIELDS,
  sections: REGISTER_INTEREST_SECTIONS,
};

export default REGISTER_INTEREST_PAGE;
